### ISSUE TITLE
The conversion package

### ISSUE THREAD

**Issue by andrewthad** [JustusAdam/mustache#10]
This is just a suggestion, not really a feature request, so feel free to disagree, since it's your library and it's still a good implementation regardless.

I recommend removing the dependency on `conversion` and `conversion-text` as well as the functions that are built on top of the `Conversion` typeclass. It's a lawless MPTC without fundeps that uses orphan instances, and I believe that your library would be better off if it didn't use it.

Again, it's just my opinion, and I assume that you probably have some particular use for the `~~>` and `~~=` operators in applications that you've built. But, if you ever start feeling uneasy about the `conversion` package, know that there's someone else who feels the same and would like to see it go.

**Comment by JustusAdam** [comment]
Nah. I don't use it at all :smile: 

I was sort of too lazy to write all the instances for converting string-likes.

I would probably be better if I removed it.

**Comment by JustusAdam** [comment]
If you provide a PR that fixes it I'll merge it.

**Comment by andrewthad** [comment]
The PR is up here: https://github.com/JustusAdam/mustache/pull/11. Specifically, you should check `src/lib/Text/Mustache/Types.hs` to make sure that I've still got instances for all the text-like things you expect.
