### ISSUE TITLE
Partial support for compile time compilation

### ISSUE THREAD

**Issue by JustusAdam** [JustusAdam/mustache#17]
- [ ] It should be possible to use partials for the compile time compilation, at least in `embedTemplate`.

    I am imagining an API somewhat like this: (names subject to change)

    ```haskell
    embedTemplate
        :: FilePath -- Search path for partials
        -> FilePath -- Template name
        -> Q Expr
    ```

- [ ] If we provide an embedding function which *does not* allow partials it should trow errors for missing partials at compile time.
The current API using `compileTemplate` will not throw any errors in this case and I think it should, but this is open for debate.

- [ ] I'd also like to evaluate whether it is possible to do some global caching for compiled templates so that

    ```haskell
    t1 = $(embedTemplate "template.mustache")

    t2 = $(embedTemplate "template.mustache")
    ```

    Only compiles the template once.

**Comment by asariley** [comment]
1 and 2). I agree, I have some code I am about to submit in a PR that addresses these points

3) While I don't know that it is impossible, if it is possible I think it would be very complicated for almost no benefit. The CPU/IO time to compile the same template twice is going to be negligible for all but the largest templates, and is easily worked around by doing 

```haskell
myTemplate = $(embedTemplate "template.mustache")

t1 = myTemplate
t2 = myTemplate
```

**Comment by JustusAdam** [comment]
Thanks for the PR. I'll have a glance at it before I merge.

I agree actually. It would also most likely make the code a lot less readable. And we're running at compile time so no one really cares if it takes a second longer.

**Comment by JustusAdam** [comment]
Your changes are live on [Hackage](https://hackage.haskell.org/package/mustache)
