### ISSUE TITLE
`MustacheConf` constructor not exported

### ISSUE THREAD

**Issue by JLimperg** [JustusAdam/mustache#18]
Hi,

in version 1.0.1, `Text.Mustache.Parser` exports `parseWithConf`, which takes a `MustacheConf` as input to customise the delimiters. However, only the default configuration can ever be constructed because the `MustacheConf` constructor (or, equivalently, a setter for its `delimiters` field) is not exported, rendering the function useless.

There's a similar problem with `MustacheState`, although in that case I see no immediate use for exporting the `Parser` type in the first place.

Cheers,
Jannis

**Comment by JustusAdam** [comment]
You are correct. I forgot to export that. I just released a fix for that (1.0.2) which should address this issue.

I'll think about what I want to do with the parser type, but you're correct, it does not need to be exported.

**Comment by JLimperg** [comment]
Cool, thank you for the quick fix. Marking this issue as resolved.
