### ISSUE TITLE
Character encoding not detected properly while reading template

### ISSUE THREAD

**Issue by reygoch** [JustusAdam/mustache#24]
I'm from Croatia, and we have characters like ČčĆćŽžĐđŠš

If I'm passing them through context, they render correctly, but if characters are present within mustache template file than they end up messed up.

I've tracked problem to your `getFile` function which uses `readFile` from `Data.Text.IO`. This is a problem, because `readFile` uses current system coding page, which can differ from encoding of a file that is being red.

I had to switch my os coding page with `chcp` from `852` to `65001` to make it work.

This could be fixed with `setLocaleEncoding` from `GHC.IO` package, but it's kind of hacky. Maybe add option to explicitly set encoding for our templates?

**Comment by JustusAdam** [comment]
I'd prefer not to have to change the API of the compilation functions.
In theory you can read the file in yourself and compile the read `Text` with `Mustache.Parser.parse`, the downside however is that you have to compile partials yourself.
If you have the compiled template you can get the partials with `Mustache.Compile.getPartials` and this needs to be done recursively of course to get nested partials as well.

**Comment by reygoch** [comment]
Ok, I guess we can close this than.
