### ISSUE TITLE
Can't render 2nd level partials with automatic compile.

### ISSUE THREAD

**Issue by reygoch** [JustusAdam/mustache#25]
I have `main.mustache` that looks like this:

**main.mustache**
```
Hello from {{>partial01.mustache}}
```

**partial01.mustache**
```
Partial 01 and {{>partial02.mustache}}
```

**partial02.mustache**
```
Partial 02
```

I'm expecting to see : `Hello from Partial 01 and Partial 02` but I just get `Hello from Partial 01 and` when I run following :

```
test :: IO Text
test = do
    template <- automaticCompile templateSearchPath "main.mustache"
    return $ renderTemplate template $ object
```

Does automatic compile does only includes for main template? If so, how can I get around that?

**Comment by reygoch** [comment]
It says that in the documentation that :

> `automaticCompile` not only finds and compiles the template for you, it also recursively finds any partials included in the template as well, compiles them and stores them in the partials hash attached to the resulting template.

So I'm guessing this is a bug. No?

**Comment by JustusAdam** [comment]
Yes that is definitely a bug.

I am currently in the process of changing the compilation method, because the current one is too complicated (the implementation), it should fix that bug as well.

I might have a look at this specific issue first though to see if I can fix it quickly.

**Comment by reygoch** [comment]
@JustusAdam are you doing it today? If no, I think I'll make something temporary today

**Comment by JustusAdam** [comment]
I'm not sure, probably won't get it done today.

**Comment by JustusAdam** [comment]
I looked into it a bit and it turns out the bug is not in `automaticCompile`. It finds the partials as it should, however the substitution function `substitute'` doesn't use the right partials cache. I'll investigate further, perhaps this is easy to fix after all.

**Comment by JustusAdam** [comment]
I found the bug and fixed it. Version 2.1.2 should work properly for you 😉
