### ISSUE TITLE
Using Lambdas

### ISSUE THREAD

**Issue by ChrisPenner** [JustusAdam/mustache#30]
Hey there; I'm attempting to use lambdas in my templates, and as far as I can tell from the hackage docs they exist; but I'm not really sure how to use them.

Is there any way to rig up a simple (Value -> Text) function in as a lambda? or (Value -> Value)? I'm working with Aeson types mostly. I suppose to generalize it would be something like `(ToMustache a, ToMustache b) => a -> b`.

Mostly just wanting to run little functions like 'truncate' to cut off descriptions, etc.

Or if you could instruct me in how to use the existing lambdas that would be great! Thanks!

**Comment by JustusAdam** [comment]
Hmm I think you're right, I should add a better documentation section ...

So currently there are three instances for functions already. (see also the [docs](http://hackage.haskell.org/package/mustache-2.1.4/docs/Text-Mustache-Types.html#t:ToMustache)

```
ToMustache (Context Value -> STree -> String)
ToMustache (Context Value -> STree -> Text)
ToMustache (Context Value -> STree -> Text)
ToMustache (Context Value -> STree -> STree)
ToMustache (STree -> Text)
ToMustache (STree -> STree)
```

This means you can simply call `toMustache` on any function with one of those signatures.

As for how to use it:

`data Context α = Context [α] α`  is like a zipper. It is the current position in the substituted Value.
the first argument is a list of parent nodes and the second argument is the current node.
The usual semantics for substitution are to look first in the current node then traverse the parent nodes back and look for matches.

and `STree` is the syntax tree for the section on which the lambda has been called.

And I just realize that there is no way to substitute the `STree` with the `Context` ... At least none is exposed. I should probably fix that.

So say I add the required function, then you can write things like:

```hs
lam = toMustache $ \context content ->
    let sub = substituteContext context content
    in truncate sub
```

**Comment by JustusAdam** [comment]
I started work on making the lambdas usable. If I have the time I might even finish it today ;)

**Comment by JustusAdam** [comment]
I managed to finish it. Version 2.2.2 has the tools necessary to work with lambdas.

Edit to my example from above:

```hs
lam = toMustache $ \content -> do
    (_, sub) <- catchSubstitute $ substituteAST content
    return $ truncate sub

```

**Comment by ChrisPenner** [comment]
Thanks for doing that work! Might I also suggest adding the following tool; it's a bit much to expect users to figure all that out for themselves, especially without much documentation.

A combinator for creating lambdas like the following is what I would primarily need and would be happy with:

```haskell
overText :: (T.Text -> T.Text) -> M.Value
overText f = M.toMustache $ \content -> do
  (_, sub) <- M.catchSubstitute $ M.substituteAST content
  return $ f sub
```

**Comment by JustusAdam** [comment]
Sure, sounds reasonable.

**Comment by ChrisPenner** [comment]
I addressed some issues in https://github.com/JustusAdam/mustache/pull/31

**Comment by chrissound** [comment]
@ChrisPenner do you have any example code you could share for this? 

@JustusAdam I've tried defining the function mentioned earlier but get an error of:
```
    • No instance for (RealFrac Text) arising from a use of ‘truncate’
    • In the second argument of ‘($)’, namely ‘truncate sub’
      In a stmt of a 'do' block: return $ truncate sub
      In the expression:
        do { (_, sub) <- catchSubstitute $ substituteAST content;
             return $ truncate sub }
```
Could you possibly show how to define a simple 'id' `Lambda` type?

**Comment by JustusAdam** [comment]
Oh I am sorry, but the `truncate` function was what Chris mentioned he wanted to define in the original issue. So basically `truncate` in this example is your function that does the work. I you want `id` simply replace `truncate` with `id`.

That said I see there is more need for documentation, I'll try to add a little tutorial on lambdas when I get the time.
