### ISSUE TITLE
Error in $: Failed reading: satisfy

### ISSUE THREAD

**Issue by YuMingLiao** [JustusAdam/mustache#39]
It produce an error in the first example [here](http://mustache.github.io/mustache.5.html)
```
template:

Hello {{name}}
You have just won {{value}} dollars!
{{#in_ca}}
Well, {{taxed_value}} dollars, after taxes.
{{/in_ca}}
```
```
data:
{
  "name": "Chris",
  "value": 10000,
  "taxed_value": 10000 - (10000 * 0.4),
  "in_ca": true
}
```
But if I changed the third line to `"taxed_value": 6000,`, it works.
```
Hello Chris
You have just won 10000 dollars!
Well, 6000 dollars, after taxes.
```

I don't know what happened. So I report it here.

**Comment by JustusAdam** [comment]
Are you sure that arithmetic operations are allowed as json values?

Looking at the json [specification](http://www.json.org/) (`number` section) it seems as though only numeric literals of the form `12345.678E+21` are allowed, with the fractional part (`.678`) and the exponential part (`E+21`) being independently optional.

So it seems the reason this doesn't work is not the library but the json standard itself.

This leaves you with the option to

- use literals in the data file
- write a Haskell file and use Haskell data directly as input, that'll allow you to use these kinds of expressions. The [hackage entry](http://hackage.haskell.org/package/mustache) for this library has documentation to help you get started with using this library
- use a data format that allows simple computations, such as [dhall](http://hackage.haskell.org/package/dhall). However this still means you have to write the program that reads the data file and the template and does the substitution. Though you could probably reuse a lot of code from the [mustache executable](https://github.com/JustusAdam/mustache/blob/master/app/Main.hs)

**Comment by YuMingLiao** [comment]
Oops! I guess I confused hash with json. silly mistakes....... Thank you for the detailed guidance!
