### ISSUE TITLE
`Lift Text` instance is now available in Data.Text causing compilation failure

### ISSUE THREAD

**Issue by agentm** [JustusAdam/mustache#41]
mustache fails to compile against [Data.Text 1.2.4.0](http://hackage.haskell.org/package/text-1.2.4.0/changelog) because this latest release (uploaded August 10, 2019) includes its own `Lift Text` instance.

The compilation error is: 

```
[3 of 8] Compiling Text.Mustache.Internal.Types ( src/Text/Mustache/Internal/Types.hs, dist/build/Text/Mustache/Internal/Types.o )

src/Text/Mustache/Internal/Types.hs:350:10: error:
    Duplicate instance declarations:
      instance Lift Text
        -- Defined at src/Text/Mustache/Internal/Types.hs:350:10
      instance Lift Text -- Defined in ‘Data.Text’
    |
350 | instance Lift Text where
    |          ^^^^^^^^^
```

mustache should probably remove this instance and add a version dependency on this specific version of `Data.Text`.

**Comment by gedigi** [comment]
would it be possible to have a `2.3.1` that includes this fix?

**Comment by tomsmeding** [comment]
@JustusAdam Appreciating the fact that you are probably busy enough with research, I as a random internet stranger would like to note that currently, a plain `cabal install stack` fails due to the fact that the changes merged here have not been pushed to Hackage yet. Thanks :)

**Comment by JustusAdam** [comment]
Thanks for the reminder. Sorry for being so inactive. :pray:  I will push the changes.

**Comment by JustusAdam** [comment]
Done. Have fun :)
