### ISSUE TITLE
Keep unknown variables around during substitution

### ISSUE THREAD

**Issue by Profpatsch** [JustusAdam/mustache#52]
When a variable is missing in the `Value`, there’s essentially three options:

1. Replace with `""` and ignore
2. Error out
3. Keep the variable text verbatim in the output, e.g. `{{variable}}`.

1 and 2 are possible with this library, but 3 isn’t currently.

Why would one want 3? Basically if you have a big file in some other language, and you just want to replace one or two things in the whole file, you would like “accidental” variable syntax to be ignored. e.g. I have a document which has `{{foo}}` in the comments, and they get replaced silently.

This is just an idea, maybe the better solution here is to make 2 available from the command line util and then just fix accidental replacements as I notice them.

**Comment by JustusAdam** [comment]
Normally I would agree, however this is what mustache has specific syntax for to change the command delimiter. As a result you should effectively never have a file with "accidental" variables. In fact there is literally always a way to change the delimiter such that there are no "accidental" variables.

**Comment by Profpatsch** [comment]
I figured out to do that eventually, yes.
