### ISSUE TITLE
Instance of Exception for ParseError

### ISSUE THREAD

**Issue by andrewthad** [JustusAdam/mustache#57]
There is a trivial instance of `Exception` (just using all the default method implementations) possible for `ParseError`. This would make it possible to `throwIO` a `ParseError`. Would a PR with this be accepted?

**Comment by JustusAdam** [comment]
Hey Andrew,

I'm sorry, but `ParseError` is not a part of `mustache`, but from the `parsec` library. I am not going to export instances for a type where neither the type nor the class originate from this package, as this will inevitably cause weird clashes in downstream code. 

You are however welcome to implement those kinds of instances in your internal libraries, which should work much the same way.

Thanks.
