### ISSUE TITLE
Why is `mustache` excluded from lts-19.5 (GHC 9.0.2)?

### ISSUE THREAD

**Issue by mpilgrem** [JustusAdam/mustache#61]
I noticed that mustache is included in `lts-18.28` (GHC 8.10.7), was included in some of the GHC 9.0.2 `nightly` series (until 2022-03-03), is included in the current GHC 9.2.2 `nightly` series, but is excluded from the `lts-19.0` to `lts-19.5` series (also GHC 9.0.2).

I wondered why mustache is blocked from `lts-19.5`, if this is something that could be resolved, and if I could help (if it can).

**Comment by JustusAdam** [comment]
I think there was an issue with a version of `unoredered-containers` and `mustache` not building together, but a newer mustache version fixed that.

**Comment by JustusAdam** [comment]
Since we can't change the version in the lts retroactively it is unfortunately missing :(

**Comment by mpilgrem** [comment]
Thank you for explaining.
